version: '3.8'

services:
  aws:
    image: 'diegodisant/busyboxk8s:latest'
    volumes:
      ./config/aws/config:~/home/.aws/config
      ./credentials/aws/credentials:~/home/.aws/credentials
    entrypoint: aws
    network_mode: host
    container_name: busybox_cli_aws

  kubectl:
    image: 'diegodisant/busyboxk8s:latest'
    volumes:
      ./config/aws/config:~/home/.aws/config
      ./credentials/aws/credentials:~/home/.aws/credentials
    entrypoint: kubectl
    network_mode: host
    container_name: busybox_cli_kubectl
