#!/bin/zsh

export STYLE_TERMINATOR="\e[0m"

# TEXT FORMAT
export TEXT_BOLD="\e[1m"
export TEXT_DIM="\e[2m"
export TEXT_UNDERLINED="\e[4m"
export TEXT_BLINK="\e[5m"
export TEXT_REVERSE="\e[7m"
export TEXT_HIDDEN="\e[8m"

# TEXT COLOR
export TEXT_DEFAULT="\e[39m"
export TEXT_BLACK="\e[30m"
export TEXT_RED="\e[31m"
export TEXT_GREEN="\e[32m"
export TEXT_YELLOW="\e[33m"
export TEXT_BLUE="\e[34m"
export TEXT_MAGENTA="\e[35m"
export TEXT_CYAN="\e[36m"
export TEXT_LIGHT_GRAY="\e[37m"
export TEXT_DARK_GRAY="\e[90m"
export TEXT_LIGHT_RED="\e[91m"
export TEXT_LIGHT_GREEN="\e[92m"
export TEXT_LIGHT_YELLOW="\e[93m"
export TEXT_LIGHT_BLUE="\e[94m"
export TEXT_LIGHT_MAGENTA="\e[95m"
export TEXT_LIGHT_CYAN="\e[96m"
export TEXT_WHITE="\e[97m"

# BACKGROUND
export BACK_DEFAULT="\e[49m"
export BACK_BLACK="\e[40m"
export BACK_RED="\e[41m"
export BACK_GREEN="\e[42m"
export BACK_YELLOW="\e[43m"
export BACK_BLUE="\e[44m"
export BACK_MAGENTA="\e[45m"
export BACK_CYAN="\e[46m"
export BACK_LIGHT_GRAY="\e[47m"
export BACK_DARK_GRAY="\e[100m"
export BACK_LIGHT_RED="\e[101m"
export BACK_LIGHT_GREEN="\e[102m"
export BACK_LIGHT_YELLOW="\e[103m"
export BACK_LIGHT_BLUE="\e[910m"
export BACK_LIGHT_MAGENTA="\e[105m"
export BACK_LIGHT_CYAN="\e[106m"
export BACK_WHITE="\e[107m"
